// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2KoQAOc0leevc-mIFJ76lstymPGE-SU',
    appId: '1:700996147394:web:9cb6ad61e634abb3ab435b',
    messagingSenderId: '700996147394',
    projectId: 'stitchsync-d9238',
    authDomain: 'stitchsync-d9238.firebaseapp.com',
    storageBucket: 'stitchsync-d9238.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7Uy7haKZGkPs0X1IH0vLiDGMiJksX5s',
    appId: '1:700996147394:android:278edf37f4bb33e8ab435b',
    messagingSenderId: '700996147394',
    projectId: 'stitchsync-d9238',
    storageBucket: 'stitchsync-d9238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGVwqL4kXIVbuuDVTGPRGQWkn0Twq17g',
    appId: '1:700996147394:ios:943c907ff630be38ab435b',
    messagingSenderId: '700996147394',
    projectId: 'stitchsync-d9238',
    storageBucket: 'stitchsync-d9238.firebasestorage.app',
    iosBundleId: 'com.jonathan.stitchsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfGVwqL4kXIVbuuDVTGPRGQWkn0Twq17g',
    appId: '1:700996147394:ios:943c907ff630be38ab435b',
    messagingSenderId: '700996147394',
    projectId: 'stitchsync-d9238',
    storageBucket: 'stitchsync-d9238.firebasestorage.app',
    iosBundleId: 'com.jonathan.stitchsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2KoQAOc0leevc-mIFJ76lstymPGE-SU',
    appId: '1:700996147394:web:34fb8692d206a02eab435b',
    messagingSenderId: '700996147394',
    projectId: 'stitchsync-d9238',
    authDomain: 'stitchsync-d9238.firebaseapp.com',
    storageBucket: 'stitchsync-d9238.firebasestorage.app',
  );
}